version: '3.8'

services:
  # ... previous services remain unchanged ...

  rocketchat:
    image: rocket.chat:latest
    container_name: innovation-chat
    restart: unless-stopped
    volumes:
      - ./docker/rocketchat/uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=${PROTOCOL:-http}://${DOMAIN:-localhost}/chat
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://${SMTP_USER}:${SMTP_PASSWORD}@${SMTP_HOST}:${SMTP_PORT}
      - From_Email=${SMTP_FROM}
      - ADMIN_USERNAME=admin
      - ADMIN_PASS_FILE=/run/secrets/chat_admin_password
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - Site_Name=Red de Innovación FP
      - Organization_Type=enterprise
      - Industry=education
      - Size=0-100
      - Country=es
      - Language=es
    depends_on:
      - mongo
    networks:
      - innovation_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/info"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:5
    container_name: innovation-mongo
    restart: unless-stopped
    command: mongod --oplogSize 128 --replSet rs0
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/dump:/dump
    networks:
      - innovation_net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongo-init-replica:
    image: mongo:5
    container_name: innovation-mongo-init
    restart: "no"
    command: >
      bash -c "sleep 10 && mongosh --host mongo:27017 --eval 'rs.initiate({_id:\"rs0\", members: [{_id:0, host:\"mongo:27017\"}]})'"
    depends_on:
      - mongo
    networks:
      - innovation_net

volumes:
  rocketchat_uploads:
    driver: local
  mongo_data:
    driver: local

secrets:
  chat_admin_password:
    file: ./secrets/chat_admin_password.txt